package io.github.warren1001.d2data.enums

enum class D2Objects(override val header: String): D2Header {
	
	CLASS("Class"),
	NAME("Name"),
	DESCRIPTION("*Description"),
	ID("*ID"),
	TOKEN("Token"),
	SELECTABLE_0("Selectable0"),
	SELECTABLE_1("Selectable1"),
	SELECTABLE_2("Selectable2"),
	SELECTABLE_3("Selectable3"),
	SELECTABLE_4("Selectable4"),
	SELECTABLE_5("Selectable5"),
	SELECTABLE_6("Selectable6"),
	SELECTABLE_7("Selectable7"),
	SIZE_X("SizeX"),
	SIZE_Y("SizeY"),
	FRAME_CNT_0("FrameCnt0"),
	FRAME_CNT_1("FrameCnt1"),
	FRAME_CNT_2("FrameCnt2"),
	FRAME_CNT_3("FrameCnt3"),
	FRAME_CNT_4("FrameCnt4"),
	FRAME_CNT_5("FrameCnt5"),
	FRAME_CNT_6("FrameCnt6"),
	FRAME_CNT_7("FrameCnt7"),
	FRAME_DELTA_0("FrameDelta0"),
	FRAME_DELTA_1("FrameDelta1"),
	FRAME_DELTA_2("FrameDelta2"),
	FRAME_DELTA_3("FrameDelta3"),
	FRAME_DELTA_4("FrameDelta4"),
	FRAME_DELTA_5("FrameDelta5"),
	FRAME_DELTA_6("FrameDelta6"),
	FRAME_DELTA_7("FrameDelta7"),
	CYCLE_ANIM_0("CycleAnim0"),
	CYCLE_ANIM_1("CycleAnim1"),
	CYCLE_ANIM_2("CycleAnim2"),
	CYCLE_ANIM_3("CycleAnim3"),
	CYCLE_ANIM_4("CycleAnim4"),
	CYCLE_ANIM_5("CycleAnim5"),
	CYCLE_ANIM_6("CycleAnim6"),
	CYCLE_ANIM_7("CycleAnim7"),
	LIT_0("Lit0"),
	LIT_1("Lit1"),
	LIT_2("Lit2"),
	LIT_3("Lit3"),
	LIT_4("Lit4"),
	LIT_5("Lit5"),
	LIT_6("Lit6"),
	LIT_7("Lit7"),
	BLOCKS_LIGHT_0("BlocksLight0"),
	BLOCKS_LIGHT_1("BlocksLight1"),
	BLOCKS_LIGHT_2("BlocksLight2"),
	BLOCKS_LIGHT_3("BlocksLight3"),
	BLOCKS_LIGHT_4("BlocksLight4"),
	BLOCKS_LIGHT_5("BlocksLight5"),
	BLOCKS_LIGHT_6("BlocksLight6"),
	BLOCKS_LIGHT_7("BlocksLight7"),
	HAS_COLLISION_0("HasCollision0"),
	HAS_COLLISION_1("HasCollision1"),
	HAS_COLLISION_2("HasCollision2"),
	HAS_COLLISION_3("HasCollision3"),
	HAS_COLLISION_4("HasCollision4"),
	HAS_COLLISION_5("HasCollision5"),
	HAS_COLLISION_6("HasCollision6"),
	HAS_COLLISION_7("HasCollision7"),
	IS_ATTACKABLE_0("IsAttackable0"),
	START_0("Start0"),
	START_1("Start1"),
	START_2("Start2"),
	START_3("Start3"),
	START_4("Start4"),
	START_5("Start5"),
	START_6("Start6"),
	START_7("Start7"),
	ENV_EFFECT("EnvEffect"),
	IS_DOOR("IsDoor"),
	BLOCKS_VIS("BlocksVis"),
	ORIENTATION("Orientation"),
	ORDER_FLAG_0("OrderFlag0"),
	ORDER_FLAG_1("OrderFlag1"),
	ORDER_FLAG_2("OrderFlag2"),
	ORDER_FLAG_3("OrderFlag3"),
	ORDER_FLAG_4("OrderFlag4"),
	ORDER_FLAG_5("OrderFlag5"),
	ORDER_FLAG_6("OrderFlag6"),
	ORDER_FLAG_7("OrderFlag7"),
	PRE_OPERATE("PreOperate"),
	MODE_0("Mode0"),
	MODE_1("Mode1"),
	MODE_2("Mode2"),
	MODE_3("Mode3"),
	MODE_4("Mode4"),
	MODE_5("Mode5"),
	MODE_6("Mode6"),
	MODE_7("Mode7"),
	YOFFSET("Yoffset"),
	XOFFSET("Xoffset"),
	DRAW("Draw"),
	RED("Red"),
	GREEN("Green"),
	BLUE("Blue"),
	HD("HD"),
	TR("TR"),
	LG("LG"),
	RA("RA"),
	LA("LA"),
	RH("RH"),
	LH("LH"),
	SH("SH"),
	S1("S1"),
	S2("S2"),
	S3("S3"),
	S4("S4"),
	S5("S5"),
	S6("S6"),
	S7("S7"),
	S8("S8"),
	TOTAL_PIECES("TotalPieces"),
	SUB_CLASS("SubClass"),
	X_SPACE("Xspace"),
	Y_SPACE("Yspace"),
	NAME_OFFSET("NameOffset"),
	MONSTER_OK("MonsterOK"),
	SHRINE_FUNCTION("ShrineFunction"),
	RESTORE("Restore"),
	PARM_0("Parm0"),
	PARM_1("Parm1"),
	PARM_2("Parm2"),
	PARM_3("Parm3"),
	PARM_4("Parm4"),
	LOCKABLE("Lockable"),
	GORE("Gore"),
	SYNC("Sync"),
	DAMAGE("Damage"),
	OVERLAY("Overlay"),
	COLLISION_SUBST("CollisionSubst"),
	LEFT("Left"),
	TOP("Top"),
	WIDTH("Width"),
	HEIGHT("Height"),
	OPERATE_FN("OperateFn"),
	POPULATE_FN("PopulateFn"),
	INIT_FN("InitFn"),
	CLIENT_FN("ClientFn"),
	RESTORE_VIRGINS("RestoreVirgins"),
	BLOCK_MISSILE("BlockMissile"),
	DRAW_UNDER("DrawUnder"),
	OPEN_WARP("OpenWarp"),
	AUTO_MAP("AutoMap");
	
	companion object {
		const val SHEET_NAME = "objects"
		val HEADERS = values().map { it.header }
		val UNIQUE_HEADER = CLASS
		const val HARDCODE = false
		
		val INFO = object: D2SheetInfo {
			override fun getSheetName() = SHEET_NAME
			override fun getHeaders() = HEADERS
			override fun getUniqueHeader() = UNIQUE_HEADER
			override fun isHardcode() = HARDCODE
		}
	}
	
}