package io.github.warren1001.d2data.enums

enum class D2SkillDesc(val header: String) {
	
	SKILL_DESC("skilldesc"),
	SKILL_PAGE("SkillPage"),
	SKILL_ROW("SkillRow"),
	SKILL_COLUMN("SkillColumn"),
	LIST_ROW("ListRow"),
	ICON_CEL("IconCel"),
	HIREABLE_ICON_CEL("HireableIconCel"),
	STR_NAME("str name"),
	STR_SHORT("str short"),
	STR_LONG("str long"),
	STR_ALT("str alt"),
	DESC_DAM("descdam"),
	DDAM_CALC_1("ddam calc1"),
	DDAM_CALC_2("ddam calc2"),
	P1_DM_ELEM("p1dmelem"),
	P1_DM_MIN("p1dmmin"),
	P1_DM_MAX("p1dmmax"),
	P2_DM_ELEM("p2dmelem"),
	P2_DM_MIN("p2dmmin"),
	P2_DM_MAX("p2dmmax"),
	P3_DM_ELEM("p3dmelem"),
	P3_DM_MIN("p3dmmin"),
	P3_DM_MAX("p3dmmax"),
	DESCATT("descatt"),
	DESC_MISSILE_1("descmissile1"),
	DESC_MISSILE_2("descmissile2"),
	DESC_MISSILE_3("descmissile3"),
	DESC_LINE_1("descline1"),
	DESC_TEXT_A1("desctexta1"),
	DESC_TEXT_B1("desctextb1"),
	DESC_CALC_A1("desccalca1"),
	DESC_CALC_B1("desccalcb1"),
	DESC_LINE_2("descline2"),
	DESC_TEXT_A2("desctexta2"),
	DESC_TEXT_B2("desctextb2"),
	DESC_CALC_A2("desccalca2"),
	DESC_CALC_B2("desccalcb2"),
	DESC_LINE_3("descline3"),
	DESC_TEXT_A3("desctexta3"),
	DESC_TEXT_B3("desctextb3"),
	DESC_CALC_A3("desccalca3"),
	DESC_CALC_B3("desccalcb3"),
	DESC_LINE_4("descline4"),
	DESC_TEXT_A4("desctexta4"),
	DESC_TEXT_B4("desctextb4"),
	DESC_CALC_A4("desccalca4"),
	DESC_CALC_B4("desccalcb4"),
	DESC_LINE_5("descline5"),
	DESC_TEXT_A5("desctexta5"),
	DESC_TEXT_B5("desctextb5"),
	DESC_CALC_A5("desccalca5"),
	DESC_CALC_B5("desccalcb5"),
	DESC_LINE_6("descline6"),
	DESC_TEXT_A6("desctexta6"),
	DESC_TEXT_B6("desctextb6"),
	DESC_CALC_A6("desccalca6"),
	DESC_CALC_B6("desccalcb6"),
	DSC_2_LINE_1("dsc2line1"),
	DSC_2_TEXT_A1("dsc2texta1"),
	DSC_2_TEXT_B1("dsc2textb1"),
	DSC_2_CALC_A1("dsc2calca1"),
	DSC_2_CALC_B1("dsc2calcb1"),
	DSC_2_LINE_2("dsc2line2"),
	DSC_2_TEXT_A2("dsc2texta2"),
	DSC_2_TEXT_B2("dsc2textb2"),
	DSC_2_CALC_A2("dsc2calca2"),
	DSC_2_CALC_B2("dsc2calcb2"),
	DSC_2_LINE_3("dsc2line3"),
	DSC_2_TEXT_A3("dsc2texta3"),
	DSC_2_TEXT_B3("dsc2textb3"),
	DSC_2_CALC_A3("dsc2calca3"),
	DSC_2_CALC_B3("dsc2calcb3"),
	DSC_2_LINE_4("dsc2line4"),
	DSC_2_TEXT_A4("dsc2texta4"),
	DSC_2_TEXT_B4("dsc2textb4"),
	DSC_2_CALC_A4("dsc2calca4"),
	DSC_2_CALC_B4("dsc2calcb4"),
	DSC_2_LINE_5("dsc2line5"),
	DSC_2_TEXT_A5("dsc2texta5"),
	DSC_2_TEXT_B5("dsc2textb5"),
	DSC_2_CALC_A5("dsc2calca5"),
	DSC_2_CALC_B5("dsc2calcb5"),
	DSC_3_LINE_1("dsc3line1"),
	DSC_3_TEXT_A1("dsc3texta1"),
	DSC_3_TEXT_B1("dsc3textb1"),
	DSC_3_CALC_A1("dsc3calca1"),
	DSC_3_CALC_B1("dsc3calcb1"),
	DSC_3_LINE_2("dsc3line2"),
	DSC_3_TEXT_A2("dsc3texta2"),
	DSC_3_TEXT_B2("dsc3textb2"),
	DSC_3_CALC_A2("dsc3calca2"),
	DSC_3_CALC_B2("dsc3calcb2"),
	DSC_3_LINE_3("dsc3line3"),
	DSC_3_TEXT_A3("dsc3texta3"),
	DSC_3_TEXT_B3("dsc3textb3"),
	DSC_3_CALC_A3("dsc3calca3"),
	DSC_3_CALC_B3("dsc3calcb3"),
	DSC_3_LINE_4("dsc3line4"),
	DSC_3_TEXT_A4("dsc3texta4"),
	DSC_3_TEXT_B4("dsc3textb4"),
	DSC_3_CALC_A4("dsc3calca4"),
	DSC_3_CALC_B4("dsc3calcb4"),
	DSC_3_LINE_5("dsc3line5"),
	DSC_3_TEXT_A5("dsc3texta5"),
	DSC_3_TEXT_B5("dsc3textb5"),
	DSC_3_CALC_A5("dsc3calca5"),
	DSC_3_CALC_B5("dsc3calcb5"),
	DSC_3_LINE_6("dsc3line6"),
	DSC_3_TEXT_A6("dsc3texta6"),
	DSC_3_TEXT_B6("dsc3textb6"),
	DSC_3_CALC_A6("dsc3calca6"),
	DSC_3_CALC_B6("dsc3calcb6"),
	DSC_3_LINE_7("dsc3line7"),
	DSC_3_TEXT_A7("dsc3texta7"),
	DSC_3_TEXT_B7("dsc3textb7"),
	DSC_3_CALC_A7("dsc3calca7"),
	DSC_3_CALC_B7("dsc3calcb7"),
	EOL("*eol");
	
	companion object {
		const val SHEET_NAME = "skilldesc"
		val HEADERS = values().map { it.header }
	}
	
}