package io.github.warren1001.d2data.enums

enum class D2Skills(val header: String) {
	
	SKILL("skill"),
	ID("*Id"),
	CHAR_CLASS("charclass"),
	SKILL_DESC("skilldesc"),
	SRV_ST_FUNC("srvstfunc"),
	SRV_DO_FUNC("srvdofunc"),
	SRV_STOP_FUNC("srvstopfunc"),
	PRG_STACK("prgstack"),
	SRV_PRG_FUNC_1("srvprgfunc1"),
	SRV_PRG_FUNC_2("srvprgfunc2"),
	SRV_PRG_FUNC_3("srvprgfunc3"),
	PRG_CALC_1("prgcalc1"),
	PRG_CALC_2("prgcalc2"),
	PRG_CALC_3("prgcalc3"),
	PRG_DAM("prgdam"),
	SRV_MISSILE("srvmissile"),
	DECQUANT("decquant"),
	LOB("lob"),
	SRV_MISSILE_A("srvmissilea"),
	SRV_MISSILE_B("srvmissileb"),
	SRV_MISSILE_C("srvmissilec"),
	USE_SERVER_MISSILES_ON_REMOTE_CLIENTS("useServerMissilesOnRemoteClients"),
	SRV_OVERLAY("srvoverlay"),
	AURA_FILTER("aurafilter"),
	AURA_STATE("aurastate"),
	AURA_TARGET_STATE("auratargetstate"),
	AURA_LEN_CALC("auralencalc"),
	AURA_RANGE_CALC("aurarangecalc"),
	AURA_STAT_1("aurastat1"),
	AURA_STAT_CALC_1("aurastatcalc1"),
	AURA_STAT_2("aurastat2"),
	AURA_STAT_CALC_2("aurastatcalc2"),
	AURA_STAT_3("aurastat3"),
	AURA_STAT_CALC_3("aurastatcalc3"),
	AURA_STAT_4("aurastat4"),
	AURA_STAT_CALC_4("aurastatcalc4"),
	AURA_STAT_5("aurastat5"),
	AURA_STAT_CALC_5("aurastatcalc5"),
	AURA_STAT_6("aurastat6"),
	AURA_STAT_CALC_6("aurastatcalc6"),
	AURA_EVENT_1("auraevent1"),
	AURA_EVENT_FUNC_1("auraeventfunc1"),
	AURA_EVENT_2("auraevent2"),
	AURA_EVENT_FUNC_2("auraeventfunc2"),
	AURA_EVENT_3("auraevent3"),
	AURA_EVENT_FUNC_3("auraeventfunc3"),
	PASSIVE_STATE("passivestate"),
	PASSIVE_ITYPE("passiveitype"),
	PASSIVE_REQ_WEAPON_COUNT("passivereqweaponcount"),
	PASSIVE_STAT_1("passivestat1"),
	PASSIVE_CALC_1("passivecalc1"),
	PASSIVE_STAT_2("passivestat2"),
	PASSIVE_CALC_2("passivecalc2"),
	PASSIVE_STAT_3("passivestat3"),
	PASSIVE_CALC_3("passivecalc3"),
	PASSIVE_STAT_4("passivestat4"),
	PASSIVE_CALC_4("passivecalc4"),
	PASSIVE_STAT_5("passivestat5"),
	PASSIVE_CALC_5("passivecalc5"),
	PASSIVE_STAT_6("passivestat6"),
	PASSIVE_CALC_6("passivecalc6"),
	PASSIVE_STAT_7("passivestat7"),
	PASSIVE_CALC_7("passivecalc7"),
	PASSIVE_STAT_8("passivestat8"),
	PASSIVE_CALC_8("passivecalc8"),
	PASSIVE_STAT_9("passivestat9"),
	PASSIVE_CALC_9("passivecalc9"),
	PASSIVE_STAT_10("passivestat10"),
	PASSIVE_CALC_10("passivecalc10"),
	SUMMON("summon"),
	PET_TYPE("pettype"),
	PET_MAX("petmax"),
	SUM_MODE("summode"),
	SUM_SKILL_1("sumskill1"),
	SUM_SK_1_CALC("sumsk1calc"),
	SUM_SKILL_2("sumskill2"),
	SUM_SK_2_CALC("sumsk2calc"),
	SUM_SKILL_3("sumskill3"),
	SUM_SK_3_CALC("sumsk3calc"),
	SUM_SKILL_4("sumskill4"),
	SUM_SK_4_CALC("sumsk4calc"),
	SUM_SKILL_5("sumskill5"),
	SUM_SK_5_CALC("sumsk5calc"),
	SUM_U_MOD("sumumod"),
	SUM_OVERLAY("sumoverlay"),
	ST_SUCCESS_ONLY("stsuccessonly"),
	ST_SOUND("stsound"),
	ST_SOUND_CLASS("stsoundclass"),
	ST_SOUND_DELAY("stsounddelay"),
	WEAPON_SND("weaponsnd"),
	DO_SOUND("dosound"),
	DO_SOUND_A("dosound a"),
	DO_SOUND_B("dosound b"),
	TGT_OVERLAY("tgtoverlay"),
	TGT_SOUND("tgtsound"),
	PRG_OVERLAY("prgoverlay"),
	PRG_SOUND("prgsound"),
	CAST_OVERLAY("castoverlay"),
	CLT_OVERLAY_A("cltoverlaya"),
	CLT_OVERLAY_B("cltoverlayb"),
	CLT_ST_FUNC("cltstfunc"),
	CLT_DO_FUNC("cltdofunc"),
	CLT_STO_PFUNC("cltstopfunc"),
	CLT_PRG_FUNC_1("cltprgfunc1"),
	CLT_PRG_FUNC_2("cltprgfunc2"),
	CLT_PRG_FUNC_3("cltprgfunc3"),
	CLT_MISSILE("cltmissile"),
	CLT_MISSILE_A("cltmissilea"),
	CLT_MISSILE_B("cltmissileb"),
	CLT_MISSILE_C("cltmissilec"),
	CLT_MISSILE_D("cltmissiled"),
	CLT_CALC_1("cltcalc1"),
	CLT_CALC_1_DESC("*cltcalc1 desc"),
	CLT_CALC_2("cltcalc2"),
	CLT_CALC_2_DESC("*cltcalc2 desc"),
	CLT_CALC_3("cltcalc3"),
	CLT_CALC_3_DESC("*cltcalc3 desc"),
	WARP("warp"),
	IMMEDIATE("immediate"),
	ENHANCEABLE("enhanceable"),
	ATTACK_RANK("attackrank"),
	NO_AMMO("noammo"),
	RANGE("range"),
	WEAP_SEL("weapsel"),
	ITYPE_A1("itypea1"),
	ITYPE_A2("itypea2"),
	ITYPE_A3("itypea3"),
	ETYPE_A1("etypea1"),
	ETYPE_A2("etypea2"),
	ITYPE_B1("itypeb1"),
	ITYPE_B2("itypeb2"),
	ITYPE_B3("itypeb3"),
	ETYPE_B1("etypeb1"),
	ETYPE_B2("etypeb2"),
	ANIM("anim"),
	SEQ_TRANS("seqtrans"),
	MON_ANIM("monanim"),
	SEQ_NUM("seqnum"),
	SEQ_INPUT("seqinput"),
	DURABILITY("durability"),
	USE_ATTACK_RATE("UseAttackRate"),
	LINE_OF_SIGHT("LineOfSight"),
	TARGETABLE_ONLY("TargetableOnly"),
	SEARCH_ENEMY_XY("SearchEnemyXY"),
	SEARCH_ENEMY_NEAR("SearchEnemyNear"),
	SEARCH_OPEN_XY("SearchOpenXY"),
	SELECT_PROC("SelectProc"),
	TARGET_CORPSE("TargetCorpse"),
	TARGET_PET("TargetPet"),
	TARGET_ALLY("TargetAlly"),
	TARGET_ITEM("TargetItem"),
	ATTACK_NO_MANA("AttackNoMana"),
	TGT_PLACE_CHECK("TgtPlaceCheck"),
	KEEP_CURSOR_STATE_ON_KILL("KeepCursorStateOnKill"),
	CONTINUE_CAST_UNSELECTED("ContinueCastUnselected"),
	CLEAR_SELECTED_ON_HOLD("ClearSelectedOnHold"),
	ITEM_EFFECT("ItemEffect"),
	ITEM_CLT_EFFECT("ItemCltEffect"),
	ITEM_TGT_DO("ItemTgtDo"),
	ITEM_TARGET("ItemTarget"),
	ITEM_CHECK_START("ItemCheckStart"),
	ITEM_CLT_CHECK_START("ItemCltCheckStart"),
	ITEM_CAST_SOUND("ItemCastSound"),
	ITEM_CAST_OVERLAY("ItemCastOverlay"),
	SK_POINTS("skpoints"),
	REQ_LEVEL("reqlevel"),
	MAX_LVL("maxlvl"),
	REQ_STR("reqstr"),
	REQ_DEX("reqdex"),
	REQ_INT("reqint"),
	REQ_VIT("reqvit"),
	REQ_SKILL_1("reqskill1"),
	REQ_SKILL_2("reqskill2"),
	REQ_SKILL_3("reqskill3"),
	RESTRICT("restrict"),
	STATE_1("State1"),
	STATE_2("State2"),
	STATE_3("State3"),
	LOCAL_DELAY("localdelay"),
	GLOBAL_DELAY("globaldelay"),
	LEFT_SKILL("leftskill"),
	RIGHT_SKILL("rightskill"),
	REPEAT("repeat"),
	ALWAYS_HIT("alwayshit"),
	USE_MANA_ON_DO("usemanaondo"),
	START_MANA("startmana"),
	MIN_MANA("minmana"),
	MANA_SHIFT("manashift"),
	MANA("mana"),
	LVL_MANA("lvlmana"),
	INTERRUPT("interrupt"),
	IN_TOWN("InTown"),
	AURA("aura"),
	PERIODIC("periodic"),
	PERDELAY("perdelay"),
	FINISHING("finishing"),
	PRG_CHARGES_TO_CAST("prgchargestocast"),
	PRG_CHARGES_CONSUMED("prgchargesconsumed"),
	PASSIVE("passive"),
	PROGRESSIVE("progressive"),
	SCROLL("scroll"),
	CALC_1("calc1"),
	CALC_1_DESC("*calc1 desc"),
	CALC_2("calc2"),
	CALC_2_DESC("*calc2 desc"),
	CALC_3("calc3"),
	CALC_3_DESC("*calc3 desc"),
	CALC_4("calc4"),
	CALC_4_DESC("*calc4 desc"),
	CALC_5("calc5"),
	CALC_5_DESC("*calc5 desc"),
	CALC_6("calc6"),
	CALC_6_DESC("*calc6 desc"),
	PARAM_1("Param1"),
	PARAM_1_DESCRIPTION("*Param1 Description"),
	PARAM_2("Param2"),
	PARAM_2_DESCRIPTION("*Param2 Description"),
	PARAM_3("Param3"),
	PARAM_3_DESCRIPTION("*Param3 Description"),
	PARAM_4("Param4"),
	PARAM_4_DESCRIPTION("*Param4 Description"),
	PARAM_5("Param5"),
	PARAM_5_DESCRIPTION("*Param5 Description"),
	PARAM_6("Param6"),
	PARAM_6_DESCRIPTION("*Param6 Description"),
	PARAM_7("Param7"),
	PARAM_7_DESCRIPTION("*Param7 Description"),
	PARAM_8("Param8"),
	PARAM_8_DESCRIPTION("*Param8 Description"),
	PARAM_9("Param9"),
	PARAM_9_DESCRIPTION("*Param9 Description"),
	PARAM_10("Param10"),
	PARAM_10_DESCRIPTION("*Param10 Description2"), // wtf blizzard
	PARAM_11("Param11"),
	PARAM_11_DESCRIPTION("*Param11 Description"),
	PARAM_12("Param12"),
	PARAM_12_DESCRIPTION("*Param12 Description"),
	IN_GAME("InGame"),
	TO_HIT("ToHit"),
	LEV_TO_HIT("LevToHit"),
	TO_HIT_CALC("ToHitCalc"),
	RESULT_FLAGS("ResultFlags"),
	HIT_FLAGS("HitFlags"),
	HIT_CLASS("HitClass"),
	KICK("Kick"),
	HIT_SHIFT("HitShift"),
	SRC_DAM("SrcDam"),
	MIN_DAM("MinDam"),
	MIN_LEV_DAM_1("MinLevDam1"),
	MIN_LEV_DAM_2("MinLevDam2"),
	MIN_LEV_DAM_3("MinLevDam3"),
	MIN_LEV_DAM_4("MinLevDam4"),
	MIN_LEV_DAM_5("MinLevDam5"),
	MAX_DAM("MaxDam"),
	MAX_LEV_DAM_1("MaxLevDam1"),
	MAX_LEV_DAM_2("MaxLevDam2"),
	MAX_LEV_DAM_3("MaxLevDam3"),
	MAX_LEV_DAM_4("MaxLevDam4"),
	MAX_LEV_DAM_5("MaxLevDam5"),
	DMG_SYM_PER_CALC("DmgSymPerCalc"),
	E_TYPE("EType"),
	E_MIN("EMin"),
	E_MIN_LEV_1("EMinLev1"),
	E_MIN_LEV_2("EMinLev2"),
	E_MIN_LEV_3("EMinLev3"),
	E_MIN_LEV_4("EMinLev4"),
	E_MIN_LEV_5("EMinLev5"),
	E_MAX("EMax"),
	E_MAX_LEV_1("EMaxLev1"),
	E_MAX_LEV_2("EMaxLev2"),
	E_MAX_LEV_3("EMaxLev3"),
	E_MAX_LEV_4("EMaxLev4"),
	E_MAX_LEV_5("EMaxLev5"),
	E_DMG_SYM_PER_CALC("EDmgSymPerCalc"),
	E_LEN("ELen"),
	E_LEV_LEN_1("ELevLen1"),
	E_LEV_LEN_2("ELevLen2"),
	E_LEV_LEN_3("ELevLen3"),
	E_LEN_SYM_PER_CALC("ELenSymPerCalc"),
	AI_TYPE("aitype"),
	AI_BONUS("aibonus"),
	COST_MULT("cost mult"),
	COST_ADD("cost add"),
	EOL("*eol");
	
	companion object {
		const val SHEET_NAME = "skills"
		val HEADERS = values().map { it.header }
	}
	
}