package io.github.warren1001.d2data.impl

import io.github.warren1001.d2data.D2Sheet
import io.github.warren1001.d2data.D2SheetManager
import java.io.File

class D2CubeMain(manager: D2SheetManager, dir: File): D2Sheet(manager, dir, "cubemain") {
	
	companion object {
		
		const val DESCRIPTION = "description"
		const val ENABLED = "enabled"
		const val LADDER = "ladder"
		const val MIN_DIFF = "min diff"
		const val VERSION = "version"
		const val OP = "op"
		const val PARAM = "param"
		const val VALUE = "value"
		const val CLASS = "class"
		const val NUMINPUTS = "numinputs"
		const val INPUT_1 = "input 1"
		const val INPUT_2 = "input 2"
		const val INPUT_3 = "input 3"
		const val INPUT_4 = "input 4"
		const val INPUT_5 = "input 5"
		const val INPUT_6 = "input 6"
		const val INPUT_7 = "input 7"
		const val OUTPUT = "output"
		const val LVL = "lvl"
		const val PLVL = "plvl"
		const val ILVL = "ilvl"
		const val MOD_1 = "mod 1"
		const val MOD_1_CHANCE = "mod 1 chance"
		const val MOD_1_PARAM = "mod 1 param"
		const val MOD_1_MIN = "mod 1 min"
		const val MOD_1_MAX = "mod 1 max"
		const val MOD_2 = "mod 2"
		const val MOD_2_CHANCE = "mod 2 chance"
		const val MOD_2_PARAM = "mod 2 param"
		const val MOD_2_MIN = "mod 2 min"
		const val MOD_2_MAX = "mod 2 max"
		const val MOD_3 = "mod 3"
		const val MOD_3_CHANCE = "mod 3 chance"
		const val MOD_3_PARAM = "mod 3 param"
		const val MOD_3_MIN = "mod 3 min"
		const val MOD_3_MAX = "mod 3 max"
		const val MOD_4 = "mod 4"
		const val MOD_4_CHANCE = "mod 4 chance"
		const val MOD_4_PARAM = "mod 4 param"
		const val MOD_4_MIN = "mod 4 min"
		const val MOD_4_MAX = "mod 4 max"
		const val MOD_5 = "mod 5"
		const val MOD_5_CHANCE = "mod 5 chance"
		const val MOD_5_PARAM = "mod 5 param"
		const val MOD_5_MIN = "mod 5 min"
		const val MOD_5_MAX = "mod 5 max"
		const val OUTPUT_B = "output b"
		const val B_LVL = "b lvl"
		const val B_PLVL = "b plvl"
		const val B_ILVL = "b ilvl"
		const val B_MOD_1 = "b mod 1"
		const val B_MOD_1_CHANCE = "b mod 1 chance"
		const val B_MOD_1_PARAM = "b mod 1 param"
		const val B_MOD_1_MIN = "b mod 1 min"
		const val B_MOD_1_MAX = "b mod 1 max"
		const val B_MOD_2 = "b mod 2"
		const val B_MOD_2_CHANCE = "b mod 2 chance"
		const val B_MOD_2_PARAM = "b mod 2 param"
		const val B_MOD_2_MIN = "b mod 2 min"
		const val B_MOD_2_MAX = "b mod 2 max"
		const val B_MOD_3 = "b mod 3"
		const val B_MOD_3_CHANCE = "b mod 3 chance"
		const val B_MOD_3_PARAM = "b mod 3 param"
		const val B_MOD_3_MIN = "b mod 3 min"
		const val B_MOD_3_MAX = "b mod 3 max"
		const val B_MOD_4 = "b mod 4"
		const val B_MOD_4_CHANCE = "b mod 4 chance"
		const val B_MOD_4_PARAM = "b mod 4 param"
		const val B_MOD_4_MIN = "b mod 4 min"
		const val B_MOD_4_MAX = "b mod 4 max"
		const val B_MOD_5 = "b mod 5"
		const val B_MOD_5_CHANCE = "b mod 5 chance"
		const val B_MOD_5_PARAM = "b mod 5 param"
		const val B_MOD_5_MIN = "b mod 5 min"
		const val B_MOD_5_MAX = "b mod 5 max"
		const val OUTPUT_C = "output c"
		const val C_LVL = "c lvl"
		const val C_PLVL = "c plvl"
		const val C_ILVL = "c ilvl"
		const val C_MOD_1 = "c mod 1"
		const val C_MOD_1_CHANCE = "c mod 1 chance"
		const val C_MOD_1_PARAM = "c mod 1 param"
		const val C_MOD_1_MIN = "c mod 1 min"
		const val C_MOD_1_MAX = "c mod 1 max"
		const val C_MOD_2 = "c mod 2"
		const val C_MOD_2_CHANCE = "c mod 2 chance"
		const val C_MOD_2_PARAM = "c mod 2 param"
		const val C_MOD_2_MIN = "c mod 2 min"
		const val C_MOD_2_MAX = "c mod 2 max"
		const val C_MOD_3 = "c mod 3"
		const val C_MOD_3_CHANCE = "c mod 3 chance"
		const val C_MOD_3_PARAM = "c mod 3 param"
		const val C_MOD_3_MIN = "c mod 3 min"
		const val C_MOD_3_MAX = "c mod 3 max"
		const val C_MOD_4 = "c mod 4"
		const val C_MOD_4_CHANCE = "c mod 4 chance"
		const val C_MOD_4_PARAM = "c mod 4 param"
		const val C_MOD_4_MIN = "c mod 4 min"
		const val C_MOD_4_MAX = "c mod 4 max"
		const val C_MOD_5 = "c mod 5"
		const val C_MOD_5_CHANCE = "c mod 5 chance"
		const val C_MOD_5_PARAM = "c mod 5 param"
		const val C_MOD_5_MIN = "c mod 5 min"
		const val C_MOD_5_MAX = "c mod 5 max"
		const val EOL = "*eol"
		
	}
	
}