package io.github.warren1001.d2data.impl

import io.github.warren1001.d2data.D2Sheet
import io.github.warren1001.d2data.D2Sheets
import java.io.File

class D2MonProp(manager: D2Sheets, dir: File): D2Sheet(manager, dir, "monprop") {
	
	companion object {
		
		private val HEADERS = listOf("Id", "prop1", "chance1", "par1", "min1", "max1", "prop2", "chance2", "par2", "min2", "max2", "prop3", "chance3", "par3", "min3", "max3", "prop4", "chance4", "par4", "min4", "max4", "prop5", "chance5", "par5", "min5", "max5", "prop6", "chance6", "par6", "min6", "max6", "prop1 (N)", "chance1 (N)", "par1 (N)", "min1 (N)", "max1 (N)", "prop2 (N)", "chance2 (N)", "par2 (N)", "min2 (N)", "max2 (N)", "prop3 (N)", "chance3 (N)", "par3 (N)", "min3 (N)", "max3 (N)", "prop4 (N)", "chance4 (N)", "par4 (N)", "min4 (N)", "max4 (N)", "prop5 (N)", "chance5 (N)", "par5 (N)", "min5 (N)", "max5 (N)", "prop6 (N)", "chance6 (N)", "par6 (N)", "min6 (N)", "max6 (N)", "prop1 (H)", "chance1 (H)", "par1 (H)", "min1 (H)", "max1 (H)", "prop2 (H)", "chance2 (H)", "par2 (H)", "min2 (H)", "max2 (H)", "prop3 (H)", "chance3 (H)", "par3 (H)", "min3 (H)", "max3 (H)", "prop4 (H)", "chance4 (H)", "par4 (H)", "min4 (H)", "max4 (H)", "prop5 (H)", "chance5 (H)", "par5 (H)", "min5 (H)", "max5 (H)", "prop6 (H)", "chance6 (H)", "par6 (H)", "min6 (H)", "max6 (H)", "*eol")
		
		const val ID = "Id"
		const val PROP_1 = "prop1"
		const val CHANCE_1 = "chance1"
		const val PAR_1 = "par1"
		const val MIN_1 = "min1"
		const val MAX_1 = "max1"
		const val PROP_2 = "prop2"
		const val CHANCE_2 = "chance2"
		const val PAR_2 = "par2"
		const val MIN_2 = "min2"
		const val MAX_2 = "max2"
		const val PROP_3 = "prop3"
		const val CHANCE_3 = "chance3"
		const val PAR_3 = "par3"
		const val MIN_3 = "min3"
		const val MAX_3 = "max3"
		const val PROP_4 = "prop4"
		const val CHANCE_4 = "chance4"
		const val PAR_4 = "par4"
		const val MIN_4 = "min4"
		const val MAX_4 = "max4"
		const val PROP_5 = "prop5"
		const val CHANCE_5 = "chance5"
		const val PAR_5 = "par5"
		const val MIN_5 = "min5"
		const val MAX_5 = "max5"
		const val PROP_6 = "prop6"
		const val CHANCE_6 = "chance6"
		const val PAR_6 = "par6"
		const val MIN_6 = "min6"
		const val MAX_6 = "max6"
		const val PROP_1_NIGHTMARE = "prop1 (N)"
		const val CHANCE_1_NIGHTMARE = "chance1 (N)"
		const val PAR_1_NIGHTMARE = "par1 (N)"
		const val MIN_1_NIGHTMARE = "min1 (N)"
		const val MAX_1_NIGHTMARE = "max1 (N)"
		const val PROP_2_NIGHTMARE = "prop2 (N)"
		const val CHANCE_2_NIGHTMARE = "chance2 (N)"
		const val PAR_2_NIGHTMARE = "par2 (N)"
		const val MIN_2_NIGHTMARE = "min2 (N)"
		const val MAX_2_NIGHTMARE = "max2 (N)"
		const val PROP_3_NIGHTMARE = "prop3 (N)"
		const val CHANCE_3_NIGHTMARE = "chance3 (N)"
		const val PAR_3_NIGHTMARE = "par3 (N)"
		const val MIN_3_NIGHTMARE = "min3 (N)"
		const val MAX_3_NIGHTMARE = "max3 (N)"
		const val PROP_4_NIGHTMARE = "prop4 (N)"
		const val CHANCE_4_NIGHTMARE = "chance4 (N)"
		const val PAR_4_NIGHTMARE = "par4 (N)"
		const val MIN_4_NIGHTMARE = "min4 (N)"
		const val MAX_4_NIGHTMARE = "max4 (N)"
		const val PROP_5_NIGHTMARE = "prop5 (N)"
		const val CHANCE_5_NIGHTMARE = "chance5 (N)"
		const val PAR_5_NIGHTMARE = "par5 (N)"
		const val MIN_5_NIGHTMARE = "min5 (N)"
		const val MAX_5_NIGHTMARE = "max5 (N)"
		const val PROP_6_NIGHTMARE = "prop6 (N)"
		const val CHANCE_6_NIGHTMARE = "chance6 (N)"
		const val PAR_6_NIGHTMARE = "par6 (N)"
		const val MIN_6_NIGHTMARE = "min6 (N)"
		const val MAX_6_NIGHTMARE = "max6 (N)"
		const val PROP_1_HELL = "prop1 (H)"
		const val CHANCE_1_HELL = "chance1 (H)"
		const val PAR_1_HELL = "par1 (H)"
		const val MIN_1_HELL = "min1 (H)"
		const val MAX_1_HELL = "max1 (H)"
		const val PROP_2_HELL = "prop2 (H)"
		const val CHANCE_2_HELL = "chance2 (H)"
		const val PAR_2_HELL = "par2 (H)"
		const val MIN_2_HELL = "min2 (H)"
		const val MAX_2_HELL = "max2 (H)"
		const val PROP_3_HELL = "prop3 (H)"
		const val CHANCE_3_HELL = "chance3 (H)"
		const val PAR_3_HELL = "par3 (H)"
		const val MIN_3_HELL = "min3 (H)"
		const val MAX_3_HELL = "max3 (H)"
		const val PROP_4_HELL = "prop4 (H)"
		const val CHANCE_4_HELL = "chance4 (H)"
		const val PAR_4_HELL = "par4 (H)"
		const val MIN_4_HELL = "min4 (H)"
		const val MAX_4_HELL = "max4 (H)"
		const val PROP_5_HELL = "prop5 (H)"
		const val CHANCE_5_HELL = "chance5 (H)"
		const val PAR_5_HELL = "par5 (H)"
		const val MIN_5_HELL = "min5 (H)"
		const val MAX_5_HELL = "max5 (H)"
		const val PROP_6_HELL = "prop6 (H)"
		const val CHANCE_6_HELL = "chance6 (H)"
		const val PAR_6_HELL = "par6 (H)"
		const val MIN_6_HELL = "min6 (H)"
		const val MAX_6_HELL = "max6 (H)"
		const val EOL = "*eol"
		
	}
	
	override fun getTrueHeaders() = HEADERS
	
}